highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
#paginate: 5
port: 4000
safe: true
url: http://zachdietz1.github.io/resume
author: Zach M. Dietz

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /resume/
title: Zach Dietz's Resume
name: Zach Dietz
email: zachdietz1@gmail.com
email_full: mailto:zachdietz1@gmail.com
website: zachdietz1.github.io/home
github: zachdietz1
twitter: 
tel: +1 413 6266914
tel_full: tel:+14136266914
google_maps: 'https://www.google.com/maps/place/222+Elm+St,+Northampton,+MA+01060/@42.322186,-72.6471357,17z/data=!3m1!4b1!4m5!3m4!1s0x89e6d76c7719049f:0xdc90de6331ddd7a6!8m2!3d42.322186!4d-72.644947'
address: 222 Elm Street
postcode: '01060'
city: Northampton
country: United States
google_analytics: UA-69291029-1

